// ── Roles image reference ──────────────────────────────
// Relative path to the role reference image next to index.html.
// Leave empty ('') to hide the button.
export const ROLES_IMG_URL = 'assets/roles_en.png';

// ── Trouble Brewing role data ──────────────────────────
export const ROLES = [
  { name:'Washerwoman',   cat:'townsfolk',  align:'good' },
  { name:'Librarian',     cat:'townsfolk',  align:'good' },
  { name:'Investigator',  cat:'townsfolk',  align:'good' },
  { name:'Chef',          cat:'townsfolk',  align:'good' },
  { name:'Empath',        cat:'townsfolk',  align:'good' },
  { name:'Fortune Teller',cat:'townsfolk',  align:'good' },
  { name:'Undertaker',    cat:'townsfolk',  align:'good' },
  { name:'Monk',          cat:'townsfolk',  align:'good' },
  { name:'Ravenkeeper',   cat:'townsfolk',  align:'good' },
  { name:'Virgin',        cat:'townsfolk',  align:'good' },
  { name:'Slayer',        cat:'townsfolk',  align:'good' },
  { name:'Soldier',       cat:'townsfolk',  align:'good' },
  { name:'Mayor',         cat:'townsfolk',  align:'good' },
  { name:'Butler',        cat:'outsider',   align:'good' },
  { name:'Recluse',       cat:'outsider',   align:'good' },
  { name:'Saint',         cat:'outsider',   align:'good' },
  { name:'Poisoner',      cat:'minion',     align:'evil' },
  { name:'Spy',           cat:'minion',     align:'evil' },
  { name:'Scarlet Woman', cat:'minion',     align:'evil' },
  { name:'Baron',         cat:'minion',     align:'evil' },
  { name:'Imp',           cat:'demon',      align:'evil' },
  { name:'Apprentice',    cat:'traveler',   align:'good' },
  { name:'Barista',       cat:'traveler',   align:'good' },
  { name:'Beggar',        cat:'traveler',   align:'good' },
  { name:'Bone Collector',cat:'traveler',   align:'good' },
  { name:'Bureaucrat',    cat:'traveler',   align:'good' },
  { name:'Butcher',       cat:'traveler',   align:'good' },
  { name:'Deviant',       cat:'traveler',   align:'good' },
  { name:'Gangster',      cat:'traveler',   align:'good' },
  { name:'Gunslinger',    cat:'traveler',   align:'good' },
  { name:'Harlot',        cat:'traveler',   align:'good' },
  { name:'Judge',         cat:'traveler',   align:'good' },
  { name:'Matron',        cat:'traveler',   align:'good' },
  { name:'Scapegoat',     cat:'traveler',   align:'good' },
  { name:'Thief',         cat:'traveler',   align:'good' },
];

// ── Role icons ─────────────────────────────────────────
export const ROLE_ICONS = {
  'Washerwoman':    'https://wiki.bloodontheclocktower.com/images/8/85/Icon_washerwoman.png',
  'Librarian':      'https://wiki.bloodontheclocktower.com/images/e/e0/Icon_librarian.png',
  'Investigator':   'https://wiki.bloodontheclocktower.com/images/a/ad/Icon_investigator.png',
  'Chef':           'https://wiki.bloodontheclocktower.com/images/d/d5/Icon_chef.png',
  'Empath':         'https://wiki.bloodontheclocktower.com/images/1/13/Icon_empath.png',
  'Fortune Teller': 'https://wiki.bloodontheclocktower.com/images/9/97/Icon_fortuneteller.png',
  'Undertaker':     'https://wiki.bloodontheclocktower.com/images/0/05/Icon_undertaker.png',
  'Monk':           'https://wiki.bloodontheclocktower.com/images/7/7c/Icon_monk.png',
  'Ravenkeeper':    'https://wiki.bloodontheclocktower.com/images/e/ef/Icon_ravenkeeper.png',
  'Virgin':         'https://wiki.bloodontheclocktower.com/images/d/d3/Icon_virgin.png',
  'Slayer':         'https://wiki.bloodontheclocktower.com/images/d/d3/Icon_slayer.png',
  'Soldier':        'https://wiki.bloodontheclocktower.com/images/c/c3/Icon_soldier.png',
  'Mayor':          'https://wiki.bloodontheclocktower.com/images/a/a1/Icon_mayor.png',
  'Butler':         'https://wiki.bloodontheclocktower.com/images/1/19/Icon_butler.png',
  'Drunk':          'https://wiki.bloodontheclocktower.com/images/4/4a/Icon_drunk.png',
  'Recluse':        'https://wiki.bloodontheclocktower.com/images/6/60/Icon_recluse.png',
  'Saint':          'https://wiki.bloodontheclocktower.com/images/c/c9/Icon_saint.png',
  'Poisoner':       'https://wiki.bloodontheclocktower.com/images/b/b1/Icon_poisoner.png',
  'Spy':            'https://wiki.bloodontheclocktower.com/images/5/54/Icon_spy.png',
  'Scarlet Woman':  'https://wiki.bloodontheclocktower.com/images/1/13/Icon_scarletwoman.png',
  'Baron':          'https://wiki.bloodontheclocktower.com/images/6/6d/Icon_baron.png',
  'Imp':            'https://wiki.bloodontheclocktower.com/images/5/5c/Icon_imp.png',
  'Apprentice':     'https://wiki.bloodontheclocktower.com/images/0/03/Icon_apprentice.png',
  'Barista':        'https://wiki.bloodontheclocktower.com/images/2/24/Icon_barista.png',
  'Beggar':         'https://wiki.bloodontheclocktower.com/images/e/e3/Icon_beggar.png',
  'Bone Collector': 'https://wiki.bloodontheclocktower.com/images/9/9e/Icon_bonecollector.png',
  'Bureaucrat':     'https://wiki.bloodontheclocktower.com/images/b/b1/Icon_bureaucrat.png',
  'Butcher':        'https://wiki.bloodontheclocktower.com/images/e/e3/Icon_butcher.png',
  'Deviant':        'https://wiki.bloodontheclocktower.com/images/a/a5/Icon_deviant.png',
  'Gangster':       'https://wiki.bloodontheclocktower.com/images/a/a5/Icon_gangster.png',
  'Gunslinger':     'https://wiki.bloodontheclocktower.com/images/1/1c/Icon_gunslinger.png',
  'Harlot':         'https://wiki.bloodontheclocktower.com/images/6/60/Icon_harlot.png',
  'Judge':          'https://wiki.bloodontheclocktower.com/images/5/59/Icon_judge.png',
  'Matron':         'https://wiki.bloodontheclocktower.com/images/2/21/Icon_matron.png',
  'Scapegoat':      'https://wiki.bloodontheclocktower.com/images/3/3a/Icon_scapegoat.png',
  'Thief':          'https://wiki.bloodontheclocktower.com/images/7/77/Icon_thief.png',
};

export const CAT_LABELS = {
  townsfolk: 'Townsfolk',
  outsider:  'Outsiders',
  minion:    'Minions',
  demon:     'Demon',
  traveler:  'Travelers',
};
export const CAT_ORDER = ['townsfolk','outsider','minion','demon','traveler'];

// ── Auto Bulgarian names ───────────────────────────────
export const BG_NAMES = [
  'Александър','Ангела','Андрей','Антония','Бойко',
  'Борислав','Валентина','Васил','Георги','Даниела',
  'Денис','Димитър','Елена','Иван','Иванка',
  'Илиян','Илияна','Ирина','Калина','Красимир',
  'Кристина','Любомир','Мария','Мартин','Милена',
  'Михаил','Надя','Николай','Павел','Петър',
  'Пламена','Радослав','Росица','Симеон','Снежана',
  'Станислав','Стефан','Стефка','Тодор','Теодора',
  'Цветан','Цветелина','Христо','Христина','Ивайло',
  'Йордан','Златка','Веселин','Драгомир','Асен',
  'Галина','Деляна','Николета','Пламен','Радостина',
  'Герасим', 'Велизар', 'Генади', 'Генка', 'Генчо', 'Гергана',
];
